/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PrintConfiguration.java
 *
 * Created on Apr 5, 2010, 4:31:47 PM
 */

package com.floreantpos.config.ui;

import java.awt.Component;

import javax.print.PrintService;
import javax.print.PrintServiceLookup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JList;

import net.miginfocom.swing.MigLayout;

import com.floreantpos.config.ApplicationConfig;
import com.floreantpos.config.PrintConfig;
import com.floreantpos.ui.dialog.POSMessageDialog;

/**
 *
 * @author mshahriar
 */
public class PrintConfigurationView extends ConfigurationView {

	/** Creates new form PrintConfiguration */
	public PrintConfigurationView() {
		initComponents();
	}

	@Override
	public String getName() {
		return com.floreantpos.POSConstants.PRINT_CONFIGURATION;
	}

	@Override
	public void initialize() throws Exception {
//		cbReceiptPrinterType.setModel(new DefaultComboBoxModel(values));
//		cbKitchenPrinterType.setModel(new DefaultComboBoxModel(values));

		PrintService[] printServices = PrintServiceLookup.lookupPrintServices(null, null);
		
		cbReceiptPrinterName.setModel(new DefaultComboBoxModel(printServices));
		cbKitchenPrinterName.setModel(new DefaultComboBoxModel(printServices));
		
		PrintServiceComboRenderer comboRenderer = new PrintServiceComboRenderer();
		cbReceiptPrinterName.setRenderer(comboRenderer);
		cbKitchenPrinterName.setRenderer(comboRenderer);
		
//		cbReceiptPrinterType.setSelectedItem(PrinterType.fromString(ApplicationConfig.getString(PrintConfig.P_RECEIPT_PRINTER_TYPE, PrinterType.OS_PRINTER.getName())));
//		cbKitchenPrinterType.setSelectedItem(PrinterType.fromString(ApplicationConfig.getString(PrintConfig.P_KITCHEN_PRINTER_TYPE, PrinterType.OS_PRINTER.getName())));
		
//		tfReceiptPrinterName.setText(ApplicationConfig.getString(PrintConfig.P_JAVAPOS_PRINTER_FOR_RECEIPT, "POSPrinter"));
//		tfReceiptCashDrawerName.setText(ApplicationConfig.getString(PrintConfig.P_CASH_DRAWER_NAME, "CashDrawer"));
//		tfKitchenPrinterName.setText(ApplicationConfig.getString(PrintConfig.P_JAVAPOS_PRINTER_FOR_KITCHEN, "KitchenPrinter"));
		
		setSelectedPrinter(cbReceiptPrinterName, PrintConfig.RECEIPT_PRINTER_NAME);
		setSelectedPrinter(cbKitchenPrinterName, PrintConfig.KITCHEN_PRINTER_NAME);
		
		chkPrintReceiptOnOrderFinish.setSelected(PrintConfig.isPrintReceiptOnOrderFinish());
		chkPrintReceiptOnOrderSettle.setSelected(PrintConfig.isPrintReceiptOnOrderSettle());
		chkPrintToKitchenOnOrderFinish.setSelected(PrintConfig.isPrintToKitchenOnOrderFinish());
		chkPrintToKitchenOnOrderSettle.setSelected(PrintConfig.isPrintToKitchenOnOrderSettle());
		
		setInitialized(true);
		
		if(printServices == null || printServices.length == 0) {
			POSMessageDialog.showMessage("No printer is installed on your operating system. Please install printer and come back again.");
		}
	}

	private void setSelectedPrinter(JComboBox whichPrinter, String propertyName) {
		PrintService osDefaultPrinter = PrintServiceLookup.lookupDefaultPrintService();
		
		if(osDefaultPrinter == null) {
			return;
		}
		
		String receiptPrinterName = ApplicationConfig.getString(propertyName, osDefaultPrinter.getName());
		
		int printerCount = whichPrinter.getItemCount();
		for(int i = 0; i < printerCount; i++) {
			PrintService printService = (PrintService) whichPrinter.getItemAt(i);
			if(printService.getName().equals(receiptPrinterName)) {
				whichPrinter.setSelectedIndex(i);
				return;
			}
		}
	}

	@Override
	public boolean save() throws Exception {
		PrintService printService = (PrintService) cbReceiptPrinterName.getSelectedItem();
		ApplicationConfig.put(PrintConfig.RECEIPT_PRINTER_NAME, printService == null ? null : printService.getName());
		printService = (PrintService) cbKitchenPrinterName.getSelectedItem();
		ApplicationConfig.put(PrintConfig.KITCHEN_PRINTER_NAME, printService == null ? null : printService.getName());
		
		PrintConfig.setPrintReceiptOnOrderFinish(chkPrintReceiptOnOrderFinish.isSelected());
		PrintConfig.setPrintReceiptOnOrderSettle(chkPrintReceiptOnOrderSettle.isSelected());
		
		PrintConfig.setPrintToKitchenOnOrderFinish(chkPrintToKitchenOnOrderFinish.isSelected());
		PrintConfig.setPrintToKitchenOnOrderSettle(chkPrintToKitchenOnOrderSettle.isSelected());
		
		return true;
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        setLayout(new MigLayout("", "[][]", "[][][18px][18px][18px][18px]"));
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        add(jLabel1, "cell 0 0,alignx right");
        
                jLabel1.setText("Receipt Printer:");
        cbReceiptPrinterName = new javax.swing.JComboBox();
        add(cbReceiptPrinterName, "cell 1 0,growx");
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        add(jLabel2, "cell 0 1,alignx right");
        
                jLabel2.setText("Kitchen Printer:");
        cbKitchenPrinterName = new javax.swing.JComboBox();
        add(cbKitchenPrinterName, "cell 1 1,growx");
        
                chkPrintReceiptOnOrderFinish = new javax.swing.JCheckBox();
                
                        chkPrintReceiptOnOrderFinish.setText("Print receipt on order settle");
                        add(chkPrintReceiptOnOrderFinish, "cell 1 2,alignx left,aligny top");
        chkPrintReceiptOnOrderSettle = new javax.swing.JCheckBox();
        
                chkPrintReceiptOnOrderSettle.setText("Print receipt on order finish");
                add(chkPrintReceiptOnOrderSettle, "cell 1 3,alignx left,aligny top");
        chkPrintToKitchenOnOrderFinish = new javax.swing.JCheckBox();
        
                chkPrintToKitchenOnOrderFinish.setText("Print to kitchen on order settle");
                add(chkPrintToKitchenOnOrderFinish, "cell 1 4,alignx left,aligny top");
        chkPrintToKitchenOnOrderSettle = new javax.swing.JCheckBox();
        
                chkPrintToKitchenOnOrderSettle.setText("Print to kitchen on order finish");
                add(chkPrintToKitchenOnOrderSettle, "cell 1 5,alignx left,aligny top");
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbKitchenPrinterName;
    private javax.swing.JComboBox cbReceiptPrinterName;
    private javax.swing.JCheckBox chkPrintToKitchenOnOrderSettle;
    private javax.swing.JCheckBox chkPrintToKitchenOnOrderFinish;
    private javax.swing.JCheckBox chkPrintReceiptOnOrderSettle;
    private javax.swing.JCheckBox chkPrintReceiptOnOrderFinish;
    // End of variables declaration//GEN-END:variables
    
    private class PrintServiceComboRenderer extends DefaultListCellRenderer {
    	@Override
    	public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
    		JLabel listCellRendererComponent = (JLabel) super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
    		PrintService printService = (PrintService) value;
    		
    		if(printService != null) {
    			listCellRendererComponent.setText(printService.getName());
    		}
    		
    		return listCellRendererComponent;
    	}
    }

}
