package com.floreantpos.swing;

import java.awt.event.ActionEvent;

import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.event.EventListenerList;

import com.floreantpos.swing.event.KeypadEvent;
import com.floreantpos.swing.event.KeypadEventListener;

/**
 * 
 * @author  seliger (github: https://github.com/coresoftwaresystems/Restaurant-OPEN/blob/b875efbc2b6f66556062e93c4b61b90dd21c6429/src/com/coresoftwaresystems/swing/NumericKeypad.java)
 */
public class NumericKeypad extends javax.swing.JComponent {

	private EventListenerList eventListeners = new EventListenerList();
	private String text = "";
	private KeypadEvent keypadEvent = null;
	private boolean isProtected = false;

	/** Creates new form PasswordForm */
	public NumericKeypad() {
		initComponents();
	}

	public synchronized void removeKeypadEventListener(KeypadEventListener listener) {
		eventListeners.remove(KeypadEventListener.class, listener);
	}

	public synchronized void addKeypadEventListener(KeypadEventListener listener) {
		eventListeners.add(KeypadEventListener.class, listener);
	}

	protected synchronized void fireKeypadEvent(int eventId) {
		Object[] listeners = eventListeners.getListenerList();
		for (int i = listeners.length - 2; i >= 0; i -= 2) {
			if (listeners[i] == KeypadEventListener.class) {
				keypadEvent = new KeypadEvent(this, eventId);
				((KeypadEventListener) listeners[i + 1]).receiveKeypadEvent(keypadEvent);
			}
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		displayPanel = new javax.swing.JPanel();
		txtInput = new javax.swing.JTextField();
		keypadPanel = new javax.swing.JPanel();
		posButton7 = new com.floreantpos.swing.PosButton();
		posButton8 = new com.floreantpos.swing.PosButton();
		posButton9 = new com.floreantpos.swing.PosButton();
		posButton4 = new com.floreantpos.swing.PosButton();
		posButton5 = new com.floreantpos.swing.PosButton();
		posButton6 = new com.floreantpos.swing.PosButton();
		posButton1 = new com.floreantpos.swing.PosButton();
		posButton2 = new com.floreantpos.swing.PosButton();
		posButton3 = new com.floreantpos.swing.PosButton();
		spacerLabel1 = new javax.swing.JLabel();
		posButton0 = new com.floreantpos.swing.PosButton();
		spacerLabel2 = new javax.swing.JLabel();
		actionpadPanel = new javax.swing.JPanel();
		posButton10 = new com.floreantpos.swing.PosButton();
		posButton12 = new com.floreantpos.swing.PosButton();

		txtInput.setBackground(new java.awt.Color(240, 240, 240));
		txtInput.setEditable(false);
		txtInput.setFont(new java.awt.Font("Tahoma", 1, 18));
		txtInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		txtInput.setFocusable(false);
		txtInput.setVerifyInputWhenFocusTarget(false);

		org.jdesktop.layout.GroupLayout displayPanelLayout = new org.jdesktop.layout.GroupLayout(displayPanel);
		displayPanel.setLayout(displayPanelLayout);
		displayPanelLayout.setHorizontalGroup(displayPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
				org.jdesktop.layout.GroupLayout.TRAILING, txtInput, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE));
		displayPanelLayout.setVerticalGroup(displayPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(txtInput,
				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE));

		keypadPanel.setLayout(new java.awt.GridLayout(4, 3, 5, 5));

		posButton7.setAction(goAction);
		posButton7.setIcon(com.floreantpos.IconFactory.getIcon("7_32.png"));
		posButton7.setActionCommand("7");
		keypadPanel.add(posButton7);

		posButton8.setAction(goAction);
		posButton8.setIcon(com.floreantpos.IconFactory.getIcon("8_32.png"));
		posButton8.setActionCommand("8");
		keypadPanel.add(posButton8);

		posButton9.setAction(goAction);
		posButton9.setIcon(com.floreantpos.IconFactory.getIcon("9_32.png"));
		posButton9.setActionCommand("9");
		keypadPanel.add(posButton9);

		posButton4.setAction(goAction);
		posButton4.setIcon(com.floreantpos.IconFactory.getIcon("4_32.png"));
		posButton4.setActionCommand("4");
		keypadPanel.add(posButton4);

		posButton5.setAction(goAction);
		posButton5.setIcon(com.floreantpos.IconFactory.getIcon("5_32.png"));
		posButton5.setActionCommand("5");
		keypadPanel.add(posButton5);

		posButton6.setAction(goAction);
		posButton6.setIcon(com.floreantpos.IconFactory.getIcon("6_32.png"));
		posButton6.setActionCommand("6");
		keypadPanel.add(posButton6);

		posButton1.setAction(goAction);
		posButton1.setIcon(com.floreantpos.IconFactory.getIcon("1_32.png"));
		posButton1.setActionCommand("1");
		keypadPanel.add(posButton1);

		posButton2.setAction(goAction);
		posButton2.setIcon(com.floreantpos.IconFactory.getIcon("2_32.png"));
		posButton2.setActionCommand("2");
		keypadPanel.add(posButton2);

		posButton3.setAction(goAction);
		posButton3.setIcon(com.floreantpos.IconFactory.getIcon("3_32.png"));
		posButton3.setActionCommand("3");
		keypadPanel.add(posButton3);
		keypadPanel.add(spacerLabel1);

		posButton0.setAction(goAction);
		posButton0.setIcon(com.floreantpos.IconFactory.getIcon("0_32.png"));
		posButton0.setActionCommand("0");
		keypadPanel.add(posButton0);
		keypadPanel.add(spacerLabel2);

		actionpadPanel.setLayout(new java.awt.GridLayout(1, 1, 5, 0));

		posButton10.setAction(goAction);
		posButton10.setIcon(com.floreantpos.IconFactory.getIcon("clear_32.png"));
		posButton10.setText("CLEAR");
		actionpadPanel.add(posButton10);

		posButton12.setAction(goAction);
		posButton12.setIcon(com.floreantpos.IconFactory.getIcon("next_32.png"));
		posButton12.setText("ENTER");
		actionpadPanel.add(posButton12);

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(displayPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.add(keypadPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
				.add(actionpadPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
				layout.createSequentialGroup()
						.add(displayPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
						.add(keypadPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 218, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
						.add(actionpadPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 51, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
						.addContainerGap()));
	}// </editor-fold>
	// GEN-END:initComponents

	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JPanel actionpadPanel;
	private javax.swing.JPanel displayPanel;
	private javax.swing.JPanel keypadPanel;
	private com.floreantpos.swing.PosButton posButton0;
	private com.floreantpos.swing.PosButton posButton1;
	private com.floreantpos.swing.PosButton posButton10;
	private com.floreantpos.swing.PosButton posButton12;
	private com.floreantpos.swing.PosButton posButton2;
	private com.floreantpos.swing.PosButton posButton3;
	private com.floreantpos.swing.PosButton posButton4;
	private com.floreantpos.swing.PosButton posButton5;
	private com.floreantpos.swing.PosButton posButton6;
	private com.floreantpos.swing.PosButton posButton7;
	private com.floreantpos.swing.PosButton posButton8;
	private com.floreantpos.swing.PosButton posButton9;
	private javax.swing.JLabel spacerLabel1;
	private javax.swing.JLabel spacerLabel2;
	private javax.swing.JTextField txtInput;
	// End of variables declaration//GEN-END:variables

	Action goAction = new AbstractAction() {
		public void actionPerformed(ActionEvent e) {
			String command = e.getActionCommand();
			if (com.floreantpos.POSConstants.CLEAR.equals(command)) {
				fireKeypadEvent(KeypadEvent.CLEAR_TRIGGERED);
				txtInput.setText("");
				setText("");
			}
			else if (com.floreantpos.POSConstants.ENTER.equals(command)) {
				fireKeypadEvent(KeypadEvent.ENTER_TRIGGERED);
			}
			else {
				fireKeypadEvent(KeypadEvent.TEXT_CHANGED);
				setText(getText() + command);
			}
		}
	};

	public void setText(String text) {
		this.text = text;
		if (isProtected()) {
			txtInput.setText(text.replaceAll(".", "*"));
		}
		else {
			txtInput.setText(text);
		}
	}

	public String getText() {
		return text;
	}

	public void setProtected(boolean isProtected) {
		this.isProtected = isProtected;
	}

	public boolean isProtected() {
		return isProtected;
	}

}