/*
 * MiscTicketItemDialog.java
 *
 * Created on September 8, 2006, 10:04 PM
 */

package com.floreantpos.ui.dialog;

import java.awt.BorderLayout;
import java.awt.Font;
import java.util.List;

import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.border.TitledBorder;

import com.floreantpos.IconFactory;
import com.floreantpos.POSConstants;
import com.floreantpos.config.TerminalConfig;
import com.floreantpos.model.Tax;
import com.floreantpos.model.TicketItem;
import com.floreantpos.model.dao.TaxDAO;
import com.floreantpos.swing.ComboBoxModel;
import com.floreantpos.ui.views.NoteView;

/**
 *
 * @author  MShahriar
 */
public class MiscTicketItemDialog extends POSDialog {
    private TicketItem ticketItem;
	
    /** Creates new form MiscTicketItemDialog */
    public MiscTicketItemDialog() {
        initComponents();
        
        noteView.setNoteLength(120);
        numberSelectionView1.setDecimalAllowed(true);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        titlePanel1 = new com.floreantpos.ui.TitlePanel();
        transparentPanel1 = new com.floreantpos.swing.TransparentPanel();
        posButton1 = new com.floreantpos.swing.PosButton();
        posButton2 = new com.floreantpos.swing.PosButton();
        transparentPanel2 = new com.floreantpos.swing.TransparentPanel();
        
        noteView = new NoteView();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        titlePanel1.setTitle(com.floreantpos.POSConstants.MISC_ITEM);
        getContentPane().add(titlePanel1, java.awt.BorderLayout.NORTH);

        posButton1.setIcon(IconFactory.getIcon("/ui_icons/", "finish.png"));
        posButton1.setText(com.floreantpos.POSConstants.FINISH);
        posButton1.setPreferredSize(new java.awt.Dimension(120, 50));
        posButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doFinish(evt);
            }
        });

        transparentPanel1.add(posButton1);

        posButton2.setIcon(IconFactory.getIcon("/ui_icons/", "cancel.png"));
        posButton2.setText(com.floreantpos.POSConstants.CANCEL);
        posButton2.setPreferredSize(new java.awt.Dimension(120, 50));
        posButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doCancel(evt);
            }
        });

        transparentPanel1.add(posButton2);

        getContentPane().add(transparentPanel1, java.awt.BorderLayout.SOUTH);

        transparentPanel2.setLayout(new java.awt.BorderLayout());

        JPanel leftPanel = createLeftPanel();
        
        
        transparentPanel2.add(leftPanel, java.awt.BorderLayout.WEST);

        noteView.setBorder(javax.swing.BorderFactory.createTitledBorder(null, com.floreantpos.POSConstants.ITEM_NAME, javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        transparentPanel2.add(noteView, java.awt.BorderLayout.CENTER);
        
        

        getContentPane().add(transparentPanel2, java.awt.BorderLayout.CENTER);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-786)/2, (screenSize.height-452)/2, 786, 452);
    }// </editor-fold>//GEN-END:initComponents

	private JPanel createLeftPanel() {
		numberSelectionView1 = new com.floreantpos.ui.views.NumberSelectionView();
		numberSelectionView1.setPreferredSize(new java.awt.Dimension(220, 392));
		numberSelectionView1.setBorder(null);
        //numberSelectionView1.setTitle(com.floreantpos.POSConstants.PRICE);
        
        JPanel leftPanel = new JPanel(new BorderLayout(5, 5));
        leftPanel.add(numberSelectionView1);
        
        JPanel leftSouthPanel = new JPanel(new BorderLayout(5, 5));
        JLabel label = new JLabel(POSConstants.TAX);
        label.setFont(label.getFont().deriveFont(Font.BOLD, 12));
		leftSouthPanel.add(label, BorderLayout.WEST);
        
        cbTax = new JComboBox();
        List<Tax> taxes = TaxDAO.getInstance().findAll();
		cbTax.setModel(new ComboBoxModel(taxes));
        leftSouthPanel.add(cbTax);
        
        leftPanel.add(leftSouthPanel, BorderLayout.SOUTH);
        leftPanel.setBorder(new TitledBorder(POSConstants.PRICE));
        
        int defaultTaxId = TerminalConfig.getMiscItemDefaultTaxId();
        if(defaultTaxId != -1) {
        	for (int i = 0; i < taxes.size(); i++) {
				Tax tax = taxes.get(i);
				if(tax.getId() == defaultTaxId) {
					cbTax.setSelectedIndex(i);
					break;
				}
			}
        }
        
		return leftPanel;
	}

    private void doCancel(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doCancel
    	setCanceled(true);
    	ticketItem = null;
    	dispose();
    }//GEN-LAST:event_doCancel

    private void doFinish(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doFinish
    	setCanceled(false);
    	double amount = numberSelectionView1.getValue();
    	String itemName = noteView.getNote();
    	
    	ticketItem = new TicketItem();
    	ticketItem.setItemCount(1);
    	ticketItem.setUnitPrice(amount);
    	ticketItem.setName(itemName);
    	ticketItem.setCategoryName(com.floreantpos.POSConstants.MISC_BUTTON_TEXT);
    	ticketItem.setGroupName(com.floreantpos.POSConstants.MISC_BUTTON_TEXT);
    	ticketItem.setShouldPrintToKitchen(true);
    	Tax tax =  (Tax) cbTax.getSelectedItem();
    	if(tax != null) {
    		ticketItem.setTaxRate(tax.getRate());
    		TerminalConfig.setMiscItemDefaultTaxId(tax.getId());
    	}
    	
    	dispose();
    }//GEN-LAST:event_doFinish
    
    public TicketItem getTicketItem() {
		return ticketItem;
	}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbTax;
    private NoteView noteView;
    private com.floreantpos.ui.views.NumberSelectionView numberSelectionView1;
    private com.floreantpos.swing.PosButton posButton1;
    private com.floreantpos.swing.PosButton posButton2;
    private com.floreantpos.ui.TitlePanel titlePanel1;
    private com.floreantpos.swing.TransparentPanel transparentPanel1;
    private com.floreantpos.swing.TransparentPanel transparentPanel2;
    // End of variables declaration//GEN-END:variables
    
}
