/*
 * FoodGroupEditor.java
 *
 * Created on August 2, 2006, 8:55 PM
 */

package com.floreantpos.ui.model;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

import javax.swing.JButton;
import javax.swing.JColorChooser;
import javax.swing.JLabel;

import net.miginfocom.swing.MigLayout;

import com.floreantpos.model.MenuCategory;
import com.floreantpos.model.MenuGroup;
import com.floreantpos.model.dao.MenuCategoryDAO;
import com.floreantpos.model.dao.MenuGroupDAO;
import com.floreantpos.swing.ComboBoxModel;
import com.floreantpos.swing.FixedLengthTextField;
import com.floreantpos.swing.IntegerTextField;
import com.floreantpos.swing.MessageDialog;
import com.floreantpos.ui.BeanEditor;
import com.floreantpos.ui.dialog.BeanEditorDialog;
import com.floreantpos.util.POSUtil;

/**
 *
 * @author  MShahriar
 */
public class MenuGroupForm extends BeanEditor {

	/** Creates new form FoodGroupEditor */
	public MenuGroupForm() {
		this(new MenuGroup());
	}

	public MenuGroupForm(MenuGroup foodGroup) {
		initComponents();

		setBean(foodGroup);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
	private void initComponents() {
		setLayout(new MigLayout("", "[70px][289px,grow][6px][49px]", "[19px][][25px][][][][15px]"));
		
		jLabel1 = new javax.swing.JLabel();
		tfName = new com.floreantpos.swing.FixedLengthTextField(120);
		jLabel2 = new javax.swing.JLabel();
		cbCategory = new javax.swing.JComboBox();
		chkVisible = new javax.swing.JCheckBox();
		btnNewCategory = new javax.swing.JButton();

		jLabel1.setText(com.floreantpos.POSConstants.NAME + ":");

		jLabel2.setText(com.floreantpos.POSConstants.CATEGORY + ":");

		chkVisible.setText(com.floreantpos.POSConstants.VISIBLE);
		chkVisible.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
		chkVisible.setMargin(new java.awt.Insets(0, 0, 0, 0));

		btnNewCategory.setText("...");
		btnNewCategory.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				doNewCategory(evt);
			}
		});
		
		lblTranslatedName = new JLabel("Translated name");
		add(lblTranslatedName, "cell 0 1,alignx trailing");

		tfTranslatedName = new FixedLengthTextField(120);
		add(tfTranslatedName, "cell 1 1,growx");
		add(jLabel2, "cell 0 2,alignx left,aligny center");
		add(jLabel1, "cell 0 0,alignx left,aligny center");
		add(tfName, "cell 1 0 3 1,growx,aligny top");

		lblSortOrder = new JLabel("Sort order");
		add(lblSortOrder, "cell 0 3,alignx leading");

		tfSortOrder = new IntegerTextField();
		tfSortOrder.setColumns(10);
		add(tfSortOrder, "cell 1 3");

		lblButtonColor = new JLabel("Button color");
		add(lblButtonColor, "cell 0 4");

		btnButtonColor = new JButton("");
		btnButtonColor.setPreferredSize(new Dimension(140, 40));
		add(btnButtonColor, "cell 1 4,growy");

		lblTextColor = new JLabel("Text color");
		add(lblTextColor, "cell 0 5");

		btnTextColor = new JButton("SAMPLE TEXT");
		btnTextColor.setPreferredSize(new Dimension(140, 40));
		add(btnTextColor, "cell 1 5");
		add(chkVisible, "cell 1 6,alignx left,aligny top");
		add(cbCategory, "cell 1 2,growx,aligny top");
		add(btnNewCategory, "cell 3 2,alignx left,aligny top");

		btnButtonColor.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				Color color = JColorChooser.showDialog(MenuGroupForm.this, "Select color", btnButtonColor.getBackground());
				btnButtonColor.setBackground(color);
				btnTextColor.setBackground(color);
			}
		});

		btnTextColor.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				Color color = JColorChooser.showDialog(MenuGroupForm.this, "Select color", btnTextColor.getForeground());
				btnTextColor.setForeground(color);
			}
		});
		
		MenuCategoryDAO categoryDAO = new MenuCategoryDAO();
		List<MenuCategory> foodCategories = categoryDAO.findAll();
		cbCategory.setModel(new ComboBoxModel(foodCategories));
	}// </editor-fold>//GEN-END:initComponents

	private void doNewCategory(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doNewCategory
		try {
			MenuCategoryForm editor = new MenuCategoryForm();
			BeanEditorDialog dialog = new BeanEditorDialog(editor);
			dialog.open();
			if (!dialog.isCanceled()) {
				MenuCategory foodCategory = (MenuCategory) editor.getBean();
				ComboBoxModel model = (ComboBoxModel) cbCategory.getModel();
				model.addElement(foodCategory);
				model.setSelectedItem(foodCategory);
			}
		} catch (Exception x) {
			MessageDialog.showError(com.floreantpos.POSConstants.ERROR_MESSAGE, x);
		}
	}//GEN-LAST:event_doNewCategory

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnNewCategory;
	private javax.swing.JComboBox cbCategory;
	private javax.swing.JCheckBox chkVisible;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private com.floreantpos.swing.FixedLengthTextField tfName;
	private JLabel lblTranslatedName;
	private FixedLengthTextField tfTranslatedName;
	private JLabel lblSortOrder;
	private JLabel lblButtonColor;
	private IntegerTextField tfSortOrder;
	private JButton btnButtonColor;
	private JLabel lblTextColor;
	private JButton btnTextColor;

	// End of variables declaration//GEN-END:variables
	@Override
	public boolean save() {
		if (!updateModel())
			return false;

		MenuGroup foodGroup = (MenuGroup) getBean();

		try {
			MenuGroupDAO foodGroupDAO = new MenuGroupDAO();
			foodGroupDAO.saveOrUpdate(foodGroup);
		} catch (Exception e) {
			MessageDialog.showError(e);
			return false;
		}
		return true;
	}

	@Override
	protected void updateView() {
		MenuGroup menuGroup = (MenuGroup) getBean();
		if (menuGroup == null) {
			tfName.setText("");
			cbCategory.setSelectedItem(null);
			chkVisible.setSelected(false);
			return;
		}
		tfName.setText(menuGroup.getName());
		tfTranslatedName.setText(menuGroup.getTranslatedName());

		if (menuGroup.getSortOrder() != null) {
			tfSortOrder.setText(menuGroup.getSortOrder().toString());
		}

		if (menuGroup.getButtonColor() != null) {
			Color color = new Color(menuGroup.getButtonColor());
			btnButtonColor.setBackground(color);
			btnTextColor.setBackground(color);
		}

		if (menuGroup.getTextColor() != null) {
			Color color = new Color(menuGroup.getTextColor());
			btnTextColor.setForeground(color);
		}
		chkVisible.setSelected(menuGroup.isVisible());

		if (menuGroup.getParent() != null) {
			cbCategory.setSelectedItem(menuGroup.getParent());
		}
	}

	@Override
	protected boolean updateModel() {
		MenuGroup menuGroup = (MenuGroup) getBean();
		if (menuGroup == null) {
			return false;
		}

		String name = tfName.getText();
		if (POSUtil.isBlankOrNull(name)) {
			MessageDialog.showError("Name is required");
			return false;
		}

		MenuCategory category = (MenuCategory) cbCategory.getSelectedItem();
		if (category == null) {
			MessageDialog.showError("Category is required");
			return false;
		}

		menuGroup.setName(tfName.getText());
		
		menuGroup.setTranslatedName(tfTranslatedName.getText());
		menuGroup.setSortOrder(tfSortOrder.getInteger());

		menuGroup.setButtonColor(btnButtonColor.getBackground().getRGB());
		menuGroup.setTextColor(btnTextColor.getForeground().getRGB());

		menuGroup.setParent(category);
		menuGroup.setVisible(chkVisible.isSelected());

		return true;
	}

	public String getDisplayText() {
		MenuGroup foodGroup = (MenuGroup) getBean();
		if (foodGroup.getId() == null) {
			return "New menu group";
		}
		return "Edit menu group";
	}
}
