/*
 * PaymentTypeSelectionView.java
 *
 * Created on August 11, 2006, 7:27 PM
 */

package com.floreantpos.ui.views.payment;

/**
 *
 * @author  MShahriar
 */
public class PaymentTypeSelectionView extends com.floreantpos.swing.TransparentPanel {
    
    /** Creates new form PaymentTypeSelectionView */
    public PaymentTypeSelectionView() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        btnCashTransaction = new com.floreantpos.swing.PosButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, com.floreantpos.POSConstants.SELECT_PAYMENT_TYPE, javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        btnCashTransaction.setText(com.floreantpos.POSConstants.CASH_TRANSACTION);
        btnCashTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doCashTransaction(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(btnCashTransaction, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(btnCashTransaction, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 54, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(220, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void doCashTransaction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doCashTransaction
    }//GEN-LAST:event_doCashTransaction
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.floreantpos.swing.PosButton btnCashTransaction;
    // End of variables declaration//GEN-END:variables
    
}
